// Generated automatically by nearley, version 2.19.0
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "query", "symbols": ["object"]},
    {"name": "object", "symbols": [{"literal":"{"}, "_", {"literal":"}"}], "postprocess": function(d) { return {}; }},
    {"name": "object$ebnf$1", "symbols": []},
    {"name": "object$ebnf$1$subexpression$1", "symbols": ["_", {"literal":","}, "_", "pair"]},
    {"name": "object$ebnf$1", "symbols": ["object$ebnf$1", "object$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "object", "symbols": [{"literal":"{"}, "_", "pair", "object$ebnf$1", "_", {"literal":"}"}]},
    {"name": "operator_expression", "symbols": [{"literal":"{"}, "_", "operator_to_value", "_", {"literal":"}"}]},
    {"name": "aggregate_expression", "symbols": [{"literal":"{"}, "_", "aggregate_op", "_", {"literal":"}"}]},
    {"name": "pair", "symbols": ["field_to_value"]},
    {"name": "pair", "symbols": ["operator_to_value"]},
    {"name": "field_to_value", "symbols": ["field", "_", {"literal":":"}, "_", "value"]},
    {"name": "operator_to_value", "symbols": ["comparison_op"]},
    {"name": "operator_to_value", "symbols": ["logical_op"]},
    {"name": "operator_to_value", "symbols": ["element_op"]},
    {"name": "operator_to_value", "symbols": ["eval_op"]},
    {"name": "operator_to_value", "symbols": ["array_op"]},
    {"name": "operator_to_value", "symbols": ["comment"]},
    {"name": "comparison_op", "symbols": ["comparison_op_eq"]},
    {"name": "comparison_op", "symbols": ["comparison_op_gt"]},
    {"name": "comparison_op", "symbols": ["comparison_op_gte"]},
    {"name": "comparison_op", "symbols": ["comparison_op_in"]},
    {"name": "comparison_op", "symbols": ["comparison_op_lt"]},
    {"name": "comparison_op", "symbols": ["comparison_op_lte"]},
    {"name": "comparison_op", "symbols": ["comparison_op_ne"]},
    {"name": "comparison_op", "symbols": ["comparison_op_nin"]},
    {"name": "aggregate_op$subexpression$1", "symbols": ["aggregate_keyword"]},
    {"name": "aggregate_op$subexpression$1", "symbols": ["quote", "aggregate_keyword", "quote"]},
    {"name": "aggregate_op$subexpression$1", "symbols": ["quote2", "aggregate_keyword", "quote2"]},
    {"name": "aggregate_op", "symbols": ["aggregate_op$subexpression$1", "_", {"literal":":"}, "_", "value"]},
    {"name": "logical_op", "symbols": ["logical_op_and"]},
    {"name": "logical_op", "symbols": ["logical_op_nor"]},
    {"name": "logical_op", "symbols": ["logical_op_not"]},
    {"name": "logical_op", "symbols": ["logical_op_or"]},
    {"name": "element_op", "symbols": ["element_op_exists"]},
    {"name": "element_op", "symbols": ["element_op_type"]},
    {"name": "eval_op", "symbols": ["eval_op_expr"]},
    {"name": "eval_op", "symbols": ["eval_op_mod"]},
    {"name": "eval_op", "symbols": ["eval_op_regex"]},
    {"name": "eval_op", "symbols": ["eval_op_text"]},
    {"name": "eval_op", "symbols": ["eval_op_where"]},
    {"name": "eval_op", "symbols": ["eval_op_jsonSchema"]},
    {"name": "array_op", "symbols": ["array_op_all"]},
    {"name": "array_op", "symbols": ["array_op_elemMatch"]},
    {"name": "array_op", "symbols": ["array_op_size"]},
    {"name": "comment$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comment$subexpression$1", "symbols": ["comment$subexpression$1$string$1"]},
    {"name": "comment$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comment$subexpression$1", "symbols": ["quote", "comment$subexpression$1$string$2", "quote"]},
    {"name": "comment$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comment$subexpression$1", "symbols": ["quote2", "comment$subexpression$1$string$3", "quote2"]},
    {"name": "comment", "symbols": ["comment$subexpression$1", "_", {"literal":":"}, "_", "string_a"]},
    {"name": "comparison_op_eq$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"e"}, {"literal":"q"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_eq$subexpression$1", "symbols": ["comparison_op_eq$subexpression$1$string$1"]},
    {"name": "comparison_op_eq$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"e"}, {"literal":"q"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_eq$subexpression$1", "symbols": ["quote", "comparison_op_eq$subexpression$1$string$2", "quote"]},
    {"name": "comparison_op_eq$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"e"}, {"literal":"q"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_eq$subexpression$1", "symbols": ["quote2", "comparison_op_eq$subexpression$1$string$3", "quote2"]},
    {"name": "comparison_op_eq", "symbols": ["comparison_op_eq$subexpression$1", "_", {"literal":":"}, "_", "value"]},
    {"name": "comparison_op_gt$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"g"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_gt$subexpression$1", "symbols": ["comparison_op_gt$subexpression$1$string$1"]},
    {"name": "comparison_op_gt$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"g"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_gt$subexpression$1", "symbols": ["quote", "comparison_op_gt$subexpression$1$string$2", "quote"]},
    {"name": "comparison_op_gt$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"g"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_gt$subexpression$1", "symbols": ["quote2", "comparison_op_gt$subexpression$1$string$3", "quote2"]},
    {"name": "comparison_op_gt$subexpression$2", "symbols": ["num_a"]},
    {"name": "comparison_op_gt$subexpression$2", "symbols": ["string_a"]},
    {"name": "comparison_op_gt", "symbols": ["comparison_op_gt$subexpression$1", "_", {"literal":":"}, "_", "comparison_op_gt$subexpression$2"]},
    {"name": "comparison_op_gte$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"g"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_gte$subexpression$1", "symbols": ["comparison_op_gte$subexpression$1$string$1"]},
    {"name": "comparison_op_gte$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"g"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_gte$subexpression$1", "symbols": ["quote", "comparison_op_gte$subexpression$1$string$2", "quote"]},
    {"name": "comparison_op_gte$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"g"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_gte$subexpression$1", "symbols": ["quote2", "comparison_op_gte$subexpression$1$string$3", "quote2"]},
    {"name": "comparison_op_gte$subexpression$2", "symbols": ["num_a"]},
    {"name": "comparison_op_gte$subexpression$2", "symbols": ["string_a"]},
    {"name": "comparison_op_gte", "symbols": ["comparison_op_gte$subexpression$1", "_", {"literal":":"}, "_", "comparison_op_gte$subexpression$2"]},
    {"name": "comparison_op_in$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_in$subexpression$1", "symbols": ["comparison_op_in$subexpression$1$string$1"]},
    {"name": "comparison_op_in$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_in$subexpression$1", "symbols": ["quote", "comparison_op_in$subexpression$1$string$2", "quote"]},
    {"name": "comparison_op_in$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_in$subexpression$1", "symbols": ["quote2", "comparison_op_in$subexpression$1$string$3", "quote2"]},
    {"name": "comparison_op_in", "symbols": ["comparison_op_in$subexpression$1", "_", {"literal":":"}, "_", "array"]},
    {"name": "comparison_op_lt$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"l"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_lt$subexpression$1", "symbols": ["comparison_op_lt$subexpression$1$string$1"]},
    {"name": "comparison_op_lt$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"l"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_lt$subexpression$1", "symbols": ["quote", "comparison_op_lt$subexpression$1$string$2", "quote"]},
    {"name": "comparison_op_lt$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"l"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_lt$subexpression$1", "symbols": ["quote2", "comparison_op_lt$subexpression$1$string$3", "quote2"]},
    {"name": "comparison_op_lt$subexpression$2", "symbols": ["num_a"]},
    {"name": "comparison_op_lt$subexpression$2", "symbols": ["string_a"]},
    {"name": "comparison_op_lt", "symbols": ["comparison_op_lt$subexpression$1", "_", {"literal":":"}, "_", "comparison_op_lt$subexpression$2"]},
    {"name": "comparison_op_lte$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"l"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_lte$subexpression$1", "symbols": ["comparison_op_lte$subexpression$1$string$1"]},
    {"name": "comparison_op_lte$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"l"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_lte$subexpression$1", "symbols": ["quote", "comparison_op_lte$subexpression$1$string$2", "quote"]},
    {"name": "comparison_op_lte$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"l"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_lte$subexpression$1", "symbols": ["quote2", "comparison_op_lte$subexpression$1$string$3", "quote2"]},
    {"name": "comparison_op_lte$subexpression$2", "symbols": ["num_a"]},
    {"name": "comparison_op_lte$subexpression$2", "symbols": ["string_a"]},
    {"name": "comparison_op_lte", "symbols": ["comparison_op_lte$subexpression$1", "_", {"literal":":"}, "_", "comparison_op_lte$subexpression$2"]},
    {"name": "comparison_op_ne$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_ne$subexpression$1", "symbols": ["comparison_op_ne$subexpression$1$string$1"]},
    {"name": "comparison_op_ne$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_ne$subexpression$1", "symbols": ["quote", "comparison_op_ne$subexpression$1$string$2", "quote"]},
    {"name": "comparison_op_ne$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_ne$subexpression$1", "symbols": ["quote2", "comparison_op_ne$subexpression$1$string$3", "quote2"]},
    {"name": "comparison_op_ne", "symbols": ["comparison_op_ne$subexpression$1", "_", {"literal":":"}, "_", "value"]},
    {"name": "comparison_op_nin$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_nin$subexpression$1", "symbols": ["comparison_op_nin$subexpression$1$string$1"]},
    {"name": "comparison_op_nin$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_nin$subexpression$1", "symbols": ["quote", "comparison_op_nin$subexpression$1$string$2", "quote"]},
    {"name": "comparison_op_nin$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_op_nin$subexpression$1", "symbols": ["quote2", "comparison_op_nin$subexpression$1$string$3", "quote2"]},
    {"name": "comparison_op_nin", "symbols": ["comparison_op_nin$subexpression$1", "_", {"literal":":"}, "_", "array"]},
    {"name": "logical_op_and$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "logical_op_and$subexpression$1", "symbols": ["logical_op_and$subexpression$1$string$1"]},
    {"name": "logical_op_and$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "logical_op_and$subexpression$1", "symbols": ["quote", "logical_op_and$subexpression$1$string$2", "quote"]},
    {"name": "logical_op_and$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "logical_op_and$subexpression$1", "symbols": ["quote2", "logical_op_and$subexpression$1$string$3", "quote2"]},
    {"name": "logical_op_and", "symbols": ["logical_op_and$subexpression$1", "_", {"literal":":"}, "_", "array"]},
    {"name": "logical_op_not$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"n"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "logical_op_not$subexpression$1", "symbols": ["logical_op_not$subexpression$1$string$1"]},
    {"name": "logical_op_not$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"n"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "logical_op_not$subexpression$1", "symbols": ["quote", "logical_op_not$subexpression$1$string$2", "quote"]},
    {"name": "logical_op_not$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"n"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "logical_op_not$subexpression$1", "symbols": ["quote2", "logical_op_not$subexpression$1$string$3", "quote2"]},
    {"name": "logical_op_not", "symbols": ["logical_op_not$subexpression$1", "_", {"literal":":"}, "_", "operator_expression"]},
    {"name": "logical_op_nor$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"n"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "logical_op_nor$subexpression$1", "symbols": ["logical_op_nor$subexpression$1$string$1"]},
    {"name": "logical_op_nor$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"n"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "logical_op_nor$subexpression$1", "symbols": ["quote", "logical_op_nor$subexpression$1$string$2", "quote"]},
    {"name": "logical_op_nor$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"n"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "logical_op_nor$subexpression$1", "symbols": ["quote2", "logical_op_nor$subexpression$1$string$3", "quote2"]},
    {"name": "logical_op_nor", "symbols": ["logical_op_nor$subexpression$1", "_", {"literal":":"}, "_", "array"]},
    {"name": "logical_op_or$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "logical_op_or$subexpression$1", "symbols": ["logical_op_or$subexpression$1$string$1"]},
    {"name": "logical_op_or$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "logical_op_or$subexpression$1", "symbols": ["quote", "logical_op_or$subexpression$1$string$2", "quote"]},
    {"name": "logical_op_or$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "logical_op_or$subexpression$1", "symbols": ["quote2", "logical_op_or$subexpression$1$string$3", "quote2"]},
    {"name": "logical_op_or", "symbols": ["logical_op_or$subexpression$1", "_", {"literal":":"}, "_", "array"]},
    {"name": "element_op_exists$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"e"}, {"literal":"x"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "element_op_exists$subexpression$1", "symbols": ["element_op_exists$subexpression$1$string$1"]},
    {"name": "element_op_exists$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"e"}, {"literal":"x"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "element_op_exists$subexpression$1", "symbols": ["quote", "element_op_exists$subexpression$1$string$2", "quote"]},
    {"name": "element_op_exists$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"e"}, {"literal":"x"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "element_op_exists$subexpression$1", "symbols": ["quote2", "element_op_exists$subexpression$1$string$3", "quote2"]},
    {"name": "element_op_exists", "symbols": ["element_op_exists$subexpression$1", "_", {"literal":":"}, "_", "boolean_a"]},
    {"name": "element_op_type$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"t"}, {"literal":"y"}, {"literal":"p"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "element_op_type$subexpression$1", "symbols": ["element_op_type$subexpression$1$string$1"]},
    {"name": "element_op_type$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"t"}, {"literal":"y"}, {"literal":"p"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "element_op_type$subexpression$1", "symbols": ["quote", "element_op_type$subexpression$1$string$2", "quote"]},
    {"name": "element_op_type$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"t"}, {"literal":"y"}, {"literal":"p"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "element_op_type$subexpression$1", "symbols": ["quote2", "element_op_type$subexpression$1$string$3", "quote2"]},
    {"name": "element_op_type$subexpression$2", "symbols": ["num_a"]},
    {"name": "element_op_type$subexpression$2", "symbols": ["array_of_string"]},
    {"name": "element_op_type$subexpression$2", "symbols": ["array_of_num"]},
    {"name": "element_op_type$subexpression$2", "symbols": ["string_a"]},
    {"name": "element_op_type", "symbols": ["element_op_type$subexpression$1", "_", {"literal":":"}, "_", "element_op_type$subexpression$2"]},
    {"name": "array_op_all$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "array_op_all$subexpression$1", "symbols": ["array_op_all$subexpression$1$string$1"]},
    {"name": "array_op_all$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "array_op_all$subexpression$1", "symbols": ["quote", "array_op_all$subexpression$1$string$2", "quote"]},
    {"name": "array_op_all$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "array_op_all$subexpression$1", "symbols": ["quote2", "array_op_all$subexpression$1$string$3", "quote2"]},
    {"name": "array_op_all", "symbols": ["array_op_all$subexpression$1", "_", {"literal":":"}, "_", "array"]},
    {"name": "array_op_elemMatch$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"e"}, {"literal":"l"}, {"literal":"e"}, {"literal":"m"}, {"literal":"M"}, {"literal":"a"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "array_op_elemMatch$subexpression$1", "symbols": ["array_op_elemMatch$subexpression$1$string$1"]},
    {"name": "array_op_elemMatch$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"e"}, {"literal":"l"}, {"literal":"e"}, {"literal":"m"}, {"literal":"M"}, {"literal":"a"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "array_op_elemMatch$subexpression$1", "symbols": ["quote", "array_op_elemMatch$subexpression$1$string$2", "quote"]},
    {"name": "array_op_elemMatch$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"e"}, {"literal":"l"}, {"literal":"e"}, {"literal":"m"}, {"literal":"M"}, {"literal":"a"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "array_op_elemMatch$subexpression$1", "symbols": ["quote2", "array_op_elemMatch$subexpression$1$string$3", "quote2"]},
    {"name": "array_op_elemMatch", "symbols": ["array_op_elemMatch$subexpression$1", "_", {"literal":":"}, "_", "object"]},
    {"name": "array_op_size$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"i"}, {"literal":"z"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "array_op_size$subexpression$1", "symbols": ["array_op_size$subexpression$1$string$1"]},
    {"name": "array_op_size$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"i"}, {"literal":"z"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "array_op_size$subexpression$1", "symbols": ["quote", "array_op_size$subexpression$1$string$2", "quote"]},
    {"name": "array_op_size$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"i"}, {"literal":"z"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "array_op_size$subexpression$1", "symbols": ["quote2", "array_op_size$subexpression$1$string$3", "quote2"]},
    {"name": "array_op_size", "symbols": ["array_op_size$subexpression$1", "_", {"literal":":"}, "_", "num_a"]},
    {"name": "eval_op_expr$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"e"}, {"literal":"x"}, {"literal":"p"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_expr$subexpression$1", "symbols": ["eval_op_expr$subexpression$1$string$1"]},
    {"name": "eval_op_expr$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"e"}, {"literal":"x"}, {"literal":"p"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_expr$subexpression$1", "symbols": ["quote", "eval_op_expr$subexpression$1$string$2", "quote"]},
    {"name": "eval_op_expr$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"e"}, {"literal":"x"}, {"literal":"p"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_expr$subexpression$1", "symbols": ["quote2", "eval_op_expr$subexpression$1$string$3", "quote2"]},
    {"name": "eval_op_expr", "symbols": ["eval_op_expr$subexpression$1", "_", {"literal":":"}, "_", "aggregate_expression"]},
    {"name": "eval_op_mod$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"m"}, {"literal":"o"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_mod$subexpression$1", "symbols": ["eval_op_mod$subexpression$1$string$1"]},
    {"name": "eval_op_mod$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"m"}, {"literal":"o"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_mod$subexpression$1", "symbols": ["quote", "eval_op_mod$subexpression$1$string$2", "quote"]},
    {"name": "eval_op_mod$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"m"}, {"literal":"o"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_mod$subexpression$1", "symbols": ["quote2", "eval_op_mod$subexpression$1$string$3", "quote2"]},
    {"name": "eval_op_mod", "symbols": ["eval_op_mod$subexpression$1", "_", {"literal":":"}, "_", "array_of_num"]},
    {"name": "eval_op_regex$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"r"}, {"literal":"e"}, {"literal":"g"}, {"literal":"e"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_regex$subexpression$1", "symbols": ["eval_op_regex$subexpression$1$string$1"]},
    {"name": "eval_op_regex$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"r"}, {"literal":"e"}, {"literal":"g"}, {"literal":"e"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_regex$subexpression$1", "symbols": ["quote", "eval_op_regex$subexpression$1$string$2", "quote"]},
    {"name": "eval_op_regex$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"r"}, {"literal":"e"}, {"literal":"g"}, {"literal":"e"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_regex$subexpression$1", "symbols": ["quote2", "eval_op_regex$subexpression$1$string$3", "quote2"]},
    {"name": "eval_op_regex$ebnf$1$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"o"}, {"literal":"p"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_regex$ebnf$1$subexpression$1$ebnf$1", "symbols": ["alphabet"]},
    {"name": "eval_op_regex$ebnf$1$subexpression$1$ebnf$1", "symbols": ["eval_op_regex$ebnf$1$subexpression$1$ebnf$1", "alphabet"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "eval_op_regex$ebnf$1$subexpression$1", "symbols": ["_", {"literal":","}, "_", "eval_op_regex$ebnf$1$subexpression$1$string$1", "_", {"literal":":"}, "_", {"literal":"'"}, "eval_op_regex$ebnf$1$subexpression$1$ebnf$1", {"literal":"'"}]},
    {"name": "eval_op_regex$ebnf$1", "symbols": ["eval_op_regex$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "eval_op_regex$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "eval_op_regex", "symbols": ["eval_op_regex$subexpression$1", "_", {"literal":":"}, "_", "regex_pattern", "eval_op_regex$ebnf$1"]},
    {"name": "eval_op_text$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"t"}, {"literal":"e"}, {"literal":"x"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_text$subexpression$1", "symbols": ["eval_op_text$subexpression$1$string$1"]},
    {"name": "eval_op_text$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"t"}, {"literal":"e"}, {"literal":"x"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_text$subexpression$1", "symbols": ["quote", "eval_op_text$subexpression$1$string$2", "quote"]},
    {"name": "eval_op_text$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"t"}, {"literal":"e"}, {"literal":"x"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_text$subexpression$1", "symbols": ["quote2", "eval_op_text$subexpression$1$string$3", "quote2"]},
    {"name": "eval_op_text", "symbols": ["eval_op_text$subexpression$1", "_", {"literal":":"}, "_", {"literal":"{"}, "_", "text_params", "_", {"literal":"}"}]},
    {"name": "eval_op_where$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_where$subexpression$1", "symbols": ["eval_op_where$subexpression$1$string$1"]},
    {"name": "eval_op_where$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_where$subexpression$1", "symbols": ["quote", "eval_op_where$subexpression$1$string$2", "quote"]},
    {"name": "eval_op_where$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_where$subexpression$1", "symbols": ["quote2", "eval_op_where$subexpression$1$string$3", "quote2"]},
    {"name": "eval_op_where", "symbols": ["eval_op_where$subexpression$1", "_", {"literal":":"}, "_", "code"]},
    {"name": "eval_op_jsonSchema$subexpression$1$string$1", "symbols": [{"literal":"$"}, {"literal":"j"}, {"literal":"s"}, {"literal":"o"}, {"literal":"n"}, {"literal":"S"}, {"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"m"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_jsonSchema$subexpression$1", "symbols": ["eval_op_jsonSchema$subexpression$1$string$1"]},
    {"name": "eval_op_jsonSchema$subexpression$1$string$2", "symbols": [{"literal":"$"}, {"literal":"j"}, {"literal":"s"}, {"literal":"o"}, {"literal":"n"}, {"literal":"S"}, {"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"m"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_jsonSchema$subexpression$1", "symbols": ["quote", "eval_op_jsonSchema$subexpression$1$string$2", "quote"]},
    {"name": "eval_op_jsonSchema$subexpression$1$string$3", "symbols": [{"literal":"$"}, {"literal":"j"}, {"literal":"s"}, {"literal":"o"}, {"literal":"n"}, {"literal":"S"}, {"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"m"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "eval_op_jsonSchema$subexpression$1", "symbols": ["quote2", "eval_op_jsonSchema$subexpression$1$string$3", "quote2"]},
    {"name": "eval_op_jsonSchema", "symbols": ["eval_op_jsonSchema$subexpression$1", "_", {"literal":":"}, "_", "object"]},
    {"name": "code$string$1", "symbols": [{"literal":"f"}, {"literal":"u"}, {"literal":"n"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "code$ebnf$1$subexpression$1$ebnf$1", "symbols": []},
    {"name": "code$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": [{"literal":","}, "_", "key_a"]},
    {"name": "code$ebnf$1$subexpression$1$ebnf$1", "symbols": ["code$ebnf$1$subexpression$1$ebnf$1", "code$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "code$ebnf$1$subexpression$1", "symbols": ["key_a", "code$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "code$ebnf$1", "symbols": ["code$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "code$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "code$ebnf$2", "symbols": []},
    {"name": "code$ebnf$2", "symbols": ["code$ebnf$2", /./], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "code", "symbols": ["code$string$1", "_", {"literal":"("}, "_", "code$ebnf$1", "_", {"literal":")"}, "_", {"literal":"{"}, "code$ebnf$2", {"literal":"}"}]},
    {"name": "code", "symbols": ["string_a"]},
    {"name": "field", "symbols": ["id_a"]},
    {"name": "field", "symbols": ["key_a"]},
    {"name": "value", "symbols": ["string_a"]},
    {"name": "value", "symbols": ["num_a"]},
    {"name": "value", "symbols": ["object"]},
    {"name": "value", "symbols": ["array"]},
    {"name": "value", "symbols": ["boolean_a"]},
    {"name": "value$string$1", "symbols": [{"literal":"n"}, {"literal":"u"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "value", "symbols": ["value$string$1"]},
    {"name": "value", "symbols": ["object_lit"]},
    {"name": "array$ebnf$1$subexpression$1$ebnf$1", "symbols": []},
    {"name": "array$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": ["_", {"literal":","}, "_", "value"]},
    {"name": "array$ebnf$1$subexpression$1$ebnf$1", "symbols": ["array$ebnf$1$subexpression$1$ebnf$1", "array$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "array$ebnf$1$subexpression$1", "symbols": ["value", "array$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "array$ebnf$1", "symbols": ["array$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "array$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "array", "symbols": [{"literal":"["}, "_", "array$ebnf$1", "_", {"literal":"]"}]},
    {"name": "array_of_primitives", "symbols": ["array_of_string"]},
    {"name": "array_of_primitives", "symbols": ["array_of_bool"]},
    {"name": "array_of_primitives", "symbols": ["array_of_num"]},
    {"name": "array_of_string$ebnf$1$subexpression$1$ebnf$1", "symbols": []},
    {"name": "array_of_string$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": ["_", {"literal":","}, "_", "string_a"]},
    {"name": "array_of_string$ebnf$1$subexpression$1$ebnf$1", "symbols": ["array_of_string$ebnf$1$subexpression$1$ebnf$1", "array_of_string$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "array_of_string$ebnf$1$subexpression$1", "symbols": ["string_a", "array_of_string$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "array_of_string$ebnf$1", "symbols": ["array_of_string$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "array_of_string$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "array_of_string", "symbols": [{"literal":"["}, "_", "array_of_string$ebnf$1", "_", {"literal":"]"}]},
    {"name": "array_of_num$ebnf$1$subexpression$1$ebnf$1", "symbols": []},
    {"name": "array_of_num$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": [{"literal":","}, "_", "num_a"]},
    {"name": "array_of_num$ebnf$1$subexpression$1$ebnf$1", "symbols": ["array_of_num$ebnf$1$subexpression$1$ebnf$1", "array_of_num$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "array_of_num$ebnf$1$subexpression$1", "symbols": ["num_a", "array_of_num$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "array_of_num$ebnf$1", "symbols": ["array_of_num$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "array_of_num$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "array_of_num", "symbols": [{"literal":"["}, "_", "array_of_num$ebnf$1", "_", {"literal":"]"}]},
    {"name": "array_of_bool$ebnf$1$subexpression$1$ebnf$1", "symbols": []},
    {"name": "array_of_bool$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": ["_", {"literal":","}, "_", "boolean_a"]},
    {"name": "array_of_bool$ebnf$1$subexpression$1$ebnf$1", "symbols": ["array_of_bool$ebnf$1$subexpression$1$ebnf$1", "array_of_bool$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "array_of_bool$ebnf$1$subexpression$1", "symbols": ["boolean_a", "array_of_bool$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "array_of_bool$ebnf$1", "symbols": ["array_of_bool$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "array_of_bool$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "array_of_bool", "symbols": [{"literal":"["}, "_", "array_of_bool$ebnf$1", "_", {"literal":"]"}]},
    {"name": "string", "symbols": ["quote", "_", "lit", "_", "quote"]},
    {"name": "string", "symbols": ["quote2", "_", "lit", "_", "quote2"]},
    {"name": "id", "symbols": ["quote", "_", "key_lit", "_", "quote"]},
    {"name": "id", "symbols": ["quote2", "_", "key_lit", "_", "quote2"]},
    {"name": "key$ebnf$1", "symbols": ["alpha_numeric"]},
    {"name": "key$ebnf$1", "symbols": ["key$ebnf$1", "alpha_numeric"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "key", "symbols": ["key$ebnf$1"]},
    {"name": "key_lit$ebnf$1", "symbols": [/[^\\"\\\$']/]},
    {"name": "key_lit$ebnf$1", "symbols": ["key_lit$ebnf$1", /[^\\"\\\$']/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "key_lit", "symbols": ["key_lit$ebnf$1"]},
    {"name": "lit$ebnf$1", "symbols": []},
    {"name": "lit$ebnf$1$subexpression$1", "symbols": [{"literal":"\\"}, /[\"bfnrt\/\\]/]},
    {"name": "lit$ebnf$1$subexpression$1$string$1", "symbols": [{"literal":"\\"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "lit$ebnf$1$subexpression$1", "symbols": ["lit$ebnf$1$subexpression$1$string$1", /[a-fA-F0-9]/, /[a-fA-F0-9]/, /[a-fA-F0-9]/, /[a-fA-F0-9]/]},
    {"name": "lit$ebnf$1$subexpression$1", "symbols": [/[^"\\]/]},
    {"name": "lit$ebnf$1", "symbols": ["lit$ebnf$1", "lit$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "lit", "symbols": ["lit$ebnf$1"]},
    {"name": "simple_lit$ebnf$1", "symbols": ["alphabet"]},
    {"name": "simple_lit$ebnf$1", "symbols": ["simple_lit$ebnf$1", "alphabet"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "simple_lit", "symbols": ["simple_lit$ebnf$1"]},
    {"name": "object_lit$ebnf$1$string$1", "symbols": [{"literal":"n"}, {"literal":"e"}, {"literal":"w"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "object_lit$ebnf$1", "symbols": ["object_lit$ebnf$1$string$1"], "postprocess": id},
    {"name": "object_lit$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "object_lit$ebnf$2", "symbols": []},
    {"name": "object_lit$ebnf$2", "symbols": ["object_lit$ebnf$2", /./], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "object_lit", "symbols": ["object_lit$ebnf$1", "_", "simple_lit", {"literal":"("}, "object_lit$ebnf$2", {"literal":")"}]},
    {"name": "regex_pattern$ebnf$1", "symbols": []},
    {"name": "regex_pattern$ebnf$1", "symbols": ["regex_pattern$ebnf$1", /./], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "regex_pattern$ebnf$2$ebnf$1", "symbols": []},
    {"name": "regex_pattern$ebnf$2$ebnf$1", "symbols": ["regex_pattern$ebnf$2$ebnf$1", "alpha_numeric"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "regex_pattern$ebnf$2", "symbols": ["regex_pattern$ebnf$2$ebnf$1"], "postprocess": id},
    {"name": "regex_pattern$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "regex_pattern", "symbols": [{"literal":"/"}, "regex_pattern$ebnf$1", {"literal":"/"}, "regex_pattern$ebnf$2"]},
    {"name": "regex_pattern$ebnf$3", "symbols": []},
    {"name": "regex_pattern$ebnf$3", "symbols": ["regex_pattern$ebnf$3", /./], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "regex_pattern", "symbols": [{"literal":"'"}, "regex_pattern$ebnf$3", {"literal":"'"}]},
    {"name": "text_params$string$1", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "text_params$string$2", "symbols": [{"literal":"$"}, {"literal":"l"}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"u"}, {"literal":"a"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "text_params$string$3", "symbols": [{"literal":"$"}, {"literal":"c"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}, {"literal":"S"}, {"literal":"e"}, {"literal":"n"}, {"literal":"s"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "text_params$string$4", "symbols": [{"literal":"$"}, {"literal":"d"}, {"literal":"i"}, {"literal":"a"}, {"literal":"c"}, {"literal":"r"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"c"}, {"literal":"S"}, {"literal":"e"}, {"literal":"n"}, {"literal":"s"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "text_params", "symbols": ["text_params$string$1", "_", {"literal":":"}, "_", "string_a", "_", {"literal":","}, "_", "text_params$string$2", "_", {"literal":":"}, "_", "string_a", "_", {"literal":","}, "_", "text_params$string$3", "_", {"literal":":"}, "_", "boolean_a", "_", {"literal":","}, "_", "text_params$string$4", "_", {"literal":":"}, "_", "boolean_a"]},
    {"name": "quote", "symbols": [{"literal":"\""}]},
    {"name": "quote2", "symbols": [{"literal":"'"}]},
    {"name": "alpha_numeric", "symbols": [/[a-zA-Z0-9_]/]},
    {"name": "alphabet", "symbols": [/[a-zA-Z]/]},
    {"name": "num$ebnf$1", "symbols": [{"literal":"-"}], "postprocess": id},
    {"name": "num$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "num$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "num$subexpression$1$ebnf$1", "symbols": []},
    {"name": "num$subexpression$1$ebnf$1", "symbols": ["num$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "num$subexpression$1", "symbols": [/[1-9]/, "num$subexpression$1$ebnf$1"]},
    {"name": "num$ebnf$2$subexpression$1$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "num$ebnf$2$subexpression$1$ebnf$1", "symbols": ["num$ebnf$2$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "num$ebnf$2$subexpression$1", "symbols": [{"literal":"."}, "num$ebnf$2$subexpression$1$ebnf$1"]},
    {"name": "num$ebnf$2", "symbols": ["num$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "num$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "num$ebnf$3$subexpression$1$ebnf$1", "symbols": [/[+-]/], "postprocess": id},
    {"name": "num$ebnf$3$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "num$ebnf$3$subexpression$1$ebnf$2", "symbols": [/[0-9]/]},
    {"name": "num$ebnf$3$subexpression$1$ebnf$2", "symbols": ["num$ebnf$3$subexpression$1$ebnf$2", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "num$ebnf$3$subexpression$1", "symbols": [/[eE]/, "num$ebnf$3$subexpression$1$ebnf$1", "num$ebnf$3$subexpression$1$ebnf$2"]},
    {"name": "num$ebnf$3", "symbols": ["num$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "num$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "num", "symbols": ["num$ebnf$1", "num$subexpression$1", "num$ebnf$2", "num$ebnf$3"]},
    {"name": "boolean$string$1", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"u"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "boolean", "symbols": ["boolean$string$1"]},
    {"name": "boolean$string$2", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"l"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "boolean", "symbols": ["boolean$string$2"]},
    {"name": "_+$ebnf$1", "symbols": [/[\s]/]},
    {"name": "_+$ebnf$1", "symbols": ["_+$ebnf$1", /[\s]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_+", "symbols": ["_+$ebnf$1"], "postprocess": function(d) {return null }},
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", /[\s]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": function(d) {return null }},
    {"name": "aggregate_keyword$string$1", "symbols": [{"literal":"$"}, {"literal":"a"}, {"literal":"b"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$1"]},
    {"name": "aggregate_keyword$string$2", "symbols": [{"literal":"$"}, {"literal":"a"}, {"literal":"d"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$2"]},
    {"name": "aggregate_keyword$string$3", "symbols": [{"literal":"$"}, {"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"T"}, {"literal":"o"}, {"literal":"S"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$3"]},
    {"name": "aggregate_keyword$string$4", "symbols": [{"literal":"$"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"E"}, {"literal":"l"}, {"literal":"e"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}, {"literal":"T"}, {"literal":"r"}, {"literal":"u"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$4"]},
    {"name": "aggregate_keyword$string$5", "symbols": [{"literal":"$"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$5"]},
    {"name": "aggregate_keyword$string$6", "symbols": [{"literal":"$"}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}, {"literal":"E"}, {"literal":"l"}, {"literal":"e"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"T"}, {"literal":"r"}, {"literal":"u"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$6"]},
    {"name": "aggregate_keyword$string$7", "symbols": [{"literal":"$"}, {"literal":"a"}, {"literal":"r"}, {"literal":"r"}, {"literal":"a"}, {"literal":"y"}, {"literal":"E"}, {"literal":"l"}, {"literal":"e"}, {"literal":"m"}, {"literal":"A"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$7"]},
    {"name": "aggregate_keyword$string$8", "symbols": [{"literal":"$"}, {"literal":"a"}, {"literal":"r"}, {"literal":"r"}, {"literal":"a"}, {"literal":"y"}, {"literal":"T"}, {"literal":"o"}, {"literal":"O"}, {"literal":"b"}, {"literal":"j"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$8"]},
    {"name": "aggregate_keyword$string$9", "symbols": [{"literal":"$"}, {"literal":"a"}, {"literal":"v"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$9"]},
    {"name": "aggregate_keyword$string$10", "symbols": [{"literal":"$"}, {"literal":"c"}, {"literal":"m"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$10"]},
    {"name": "aggregate_keyword$string$11", "symbols": [{"literal":"$"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"c"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$11"]},
    {"name": "aggregate_keyword$string$12", "symbols": [{"literal":"$"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"c"}, {"literal":"a"}, {"literal":"t"}, {"literal":"A"}, {"literal":"r"}, {"literal":"r"}, {"literal":"a"}, {"literal":"y"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$12"]},
    {"name": "aggregate_keyword$string$13", "symbols": [{"literal":"$"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$13"]},
    {"name": "aggregate_keyword$string$14", "symbols": [{"literal":"$"}, {"literal":"d"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"F"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}, {"literal":"P"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$14"]},
    {"name": "aggregate_keyword$string$15", "symbols": [{"literal":"$"}, {"literal":"d"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"T"}, {"literal":"o"}, {"literal":"P"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$15"]},
    {"name": "aggregate_keyword$string$16", "symbols": [{"literal":"$"}, {"literal":"d"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"F"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}, {"literal":"S"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$16"]},
    {"name": "aggregate_keyword$string$17", "symbols": [{"literal":"$"}, {"literal":"d"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"T"}, {"literal":"o"}, {"literal":"S"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$17"]},
    {"name": "aggregate_keyword$string$18", "symbols": [{"literal":"$"}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}, {"literal":"O"}, {"literal":"f"}, {"literal":"M"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$18"]},
    {"name": "aggregate_keyword$string$19", "symbols": [{"literal":"$"}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}, {"literal":"O"}, {"literal":"f"}, {"literal":"W"}, {"literal":"e"}, {"literal":"e"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$19"]},
    {"name": "aggregate_keyword$string$20", "symbols": [{"literal":"$"}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}, {"literal":"O"}, {"literal":"f"}, {"literal":"Y"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$20"]},
    {"name": "aggregate_keyword$string$21", "symbols": [{"literal":"$"}, {"literal":"d"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$21"]},
    {"name": "aggregate_keyword$string$22", "symbols": [{"literal":"$"}, {"literal":"e"}, {"literal":"q"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$22"]},
    {"name": "aggregate_keyword$string$23", "symbols": [{"literal":"$"}, {"literal":"e"}, {"literal":"x"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$23"]},
    {"name": "aggregate_keyword$string$24", "symbols": [{"literal":"$"}, {"literal":"f"}, {"literal":"i"}, {"literal":"l"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$24"]},
    {"name": "aggregate_keyword$string$25", "symbols": [{"literal":"$"}, {"literal":"f"}, {"literal":"i"}, {"literal":"r"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$25"]},
    {"name": "aggregate_keyword$string$26", "symbols": [{"literal":"$"}, {"literal":"f"}, {"literal":"l"}, {"literal":"o"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$26"]},
    {"name": "aggregate_keyword$string$27", "symbols": [{"literal":"$"}, {"literal":"g"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$27"]},
    {"name": "aggregate_keyword$string$28", "symbols": [{"literal":"$"}, {"literal":"g"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$28"]},
    {"name": "aggregate_keyword$string$29", "symbols": [{"literal":"$"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$29"]},
    {"name": "aggregate_keyword$string$30", "symbols": [{"literal":"$"}, {"literal":"i"}, {"literal":"f"}, {"literal":"N"}, {"literal":"u"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$30"]},
    {"name": "aggregate_keyword$string$31", "symbols": [{"literal":"$"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$31"]},
    {"name": "aggregate_keyword$string$32", "symbols": [{"literal":"$"}, {"literal":"i"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"x"}, {"literal":"O"}, {"literal":"f"}, {"literal":"A"}, {"literal":"r"}, {"literal":"r"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$32"]},
    {"name": "aggregate_keyword$string$33", "symbols": [{"literal":"$"}, {"literal":"i"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"x"}, {"literal":"O"}, {"literal":"f"}, {"literal":"B"}, {"literal":"y"}, {"literal":"t"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$33"]},
    {"name": "aggregate_keyword$string$34", "symbols": [{"literal":"$"}, {"literal":"i"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"x"}, {"literal":"O"}, {"literal":"f"}, {"literal":"C"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$34"]},
    {"name": "aggregate_keyword$string$35", "symbols": [{"literal":"$"}, {"literal":"i"}, {"literal":"s"}, {"literal":"A"}, {"literal":"r"}, {"literal":"r"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$35"]},
    {"name": "aggregate_keyword$string$36", "symbols": [{"literal":"$"}, {"literal":"i"}, {"literal":"s"}, {"literal":"o"}, {"literal":"D"}, {"literal":"a"}, {"literal":"y"}, {"literal":"O"}, {"literal":"f"}, {"literal":"W"}, {"literal":"e"}, {"literal":"e"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$36"]},
    {"name": "aggregate_keyword$string$37", "symbols": [{"literal":"$"}, {"literal":"i"}, {"literal":"s"}, {"literal":"o"}, {"literal":"W"}, {"literal":"e"}, {"literal":"e"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$37"]},
    {"name": "aggregate_keyword$string$38", "symbols": [{"literal":"$"}, {"literal":"i"}, {"literal":"s"}, {"literal":"o"}, {"literal":"W"}, {"literal":"e"}, {"literal":"e"}, {"literal":"k"}, {"literal":"Y"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$38"]},
    {"name": "aggregate_keyword$string$39", "symbols": [{"literal":"$"}, {"literal":"l"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$39"]},
    {"name": "aggregate_keyword$string$40", "symbols": [{"literal":"$"}, {"literal":"l"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$40"]},
    {"name": "aggregate_keyword$string$41", "symbols": [{"literal":"$"}, {"literal":"l"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$41"]},
    {"name": "aggregate_keyword$string$42", "symbols": [{"literal":"$"}, {"literal":"l"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$42"]},
    {"name": "aggregate_keyword$string$43", "symbols": [{"literal":"$"}, {"literal":"l"}, {"literal":"o"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$43"]},
    {"name": "aggregate_keyword$string$44", "symbols": [{"literal":"$"}, {"literal":"l"}, {"literal":"o"}, {"literal":"g"}, {"literal":"1"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$44"]},
    {"name": "aggregate_keyword$string$45", "symbols": [{"literal":"$"}, {"literal":"l"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$45"]},
    {"name": "aggregate_keyword$string$46", "symbols": [{"literal":"$"}, {"literal":"l"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$46"]},
    {"name": "aggregate_keyword$string$47", "symbols": [{"literal":"$"}, {"literal":"l"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$47"]},
    {"name": "aggregate_keyword$string$48", "symbols": [{"literal":"$"}, {"literal":"m"}, {"literal":"a"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$48"]},
    {"name": "aggregate_keyword$string$49", "symbols": [{"literal":"$"}, {"literal":"m"}, {"literal":"a"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$49"]},
    {"name": "aggregate_keyword$string$50", "symbols": [{"literal":"$"}, {"literal":"m"}, {"literal":"e"}, {"literal":"r"}, {"literal":"g"}, {"literal":"e"}, {"literal":"O"}, {"literal":"b"}, {"literal":"j"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$50"]},
    {"name": "aggregate_keyword$string$51", "symbols": [{"literal":"$"}, {"literal":"m"}, {"literal":"e"}, {"literal":"t"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$51"]},
    {"name": "aggregate_keyword$string$52", "symbols": [{"literal":"$"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$52"]},
    {"name": "aggregate_keyword$string$53", "symbols": [{"literal":"$"}, {"literal":"m"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$53"]},
    {"name": "aggregate_keyword$string$54", "symbols": [{"literal":"$"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"u"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$54"]},
    {"name": "aggregate_keyword$string$55", "symbols": [{"literal":"$"}, {"literal":"m"}, {"literal":"o"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$55"]},
    {"name": "aggregate_keyword$string$56", "symbols": [{"literal":"$"}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$56"]},
    {"name": "aggregate_keyword$string$57", "symbols": [{"literal":"$"}, {"literal":"m"}, {"literal":"u"}, {"literal":"l"}, {"literal":"t"}, {"literal":"i"}, {"literal":"p"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$57"]},
    {"name": "aggregate_keyword$string$58", "symbols": [{"literal":"$"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$58"]},
    {"name": "aggregate_keyword$string$59", "symbols": [{"literal":"$"}, {"literal":"n"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$59"]},
    {"name": "aggregate_keyword$string$60", "symbols": [{"literal":"$"}, {"literal":"o"}, {"literal":"b"}, {"literal":"j"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"T"}, {"literal":"o"}, {"literal":"A"}, {"literal":"r"}, {"literal":"r"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$60"]},
    {"name": "aggregate_keyword$string$61", "symbols": [{"literal":"$"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$61"]},
    {"name": "aggregate_keyword$string$62", "symbols": [{"literal":"$"}, {"literal":"p"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$62"]},
    {"name": "aggregate_keyword$string$63", "symbols": [{"literal":"$"}, {"literal":"p"}, {"literal":"u"}, {"literal":"s"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$63"]},
    {"name": "aggregate_keyword$string$64", "symbols": [{"literal":"$"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$64"]},
    {"name": "aggregate_keyword$string$65", "symbols": [{"literal":"$"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}, {"literal":"u"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$65"]},
    {"name": "aggregate_keyword$string$66", "symbols": [{"literal":"$"}, {"literal":"r"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}, {"literal":"e"}, {"literal":"A"}, {"literal":"r"}, {"literal":"r"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$66"]},
    {"name": "aggregate_keyword$string$67", "symbols": [{"literal":"$"}, {"literal":"r"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$67"]},
    {"name": "aggregate_keyword$string$68", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$68"]},
    {"name": "aggregate_keyword$string$69", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"e"}, {"literal":"t"}, {"literal":"D"}, {"literal":"i"}, {"literal":"f"}, {"literal":"f"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$69"]},
    {"name": "aggregate_keyword$string$70", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"e"}, {"literal":"t"}, {"literal":"E"}, {"literal":"q"}, {"literal":"u"}, {"literal":"a"}, {"literal":"l"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$70"]},
    {"name": "aggregate_keyword$string$71", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"e"}, {"literal":"t"}, {"literal":"I"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$71"]},
    {"name": "aggregate_keyword$string$72", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"e"}, {"literal":"t"}, {"literal":"I"}, {"literal":"s"}, {"literal":"S"}, {"literal":"u"}, {"literal":"b"}, {"literal":"s"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$72"]},
    {"name": "aggregate_keyword$string$73", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"e"}, {"literal":"t"}, {"literal":"U"}, {"literal":"n"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$73"]},
    {"name": "aggregate_keyword$string$74", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"i"}, {"literal":"z"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$74"]},
    {"name": "aggregate_keyword$string$75", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"l"}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$75"]},
    {"name": "aggregate_keyword$string$76", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"p"}, {"literal":"l"}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$76"]},
    {"name": "aggregate_keyword$string$77", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"q"}, {"literal":"r"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$77"]},
    {"name": "aggregate_keyword$string$78", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"t"}, {"literal":"d"}, {"literal":"D"}, {"literal":"e"}, {"literal":"v"}, {"literal":"P"}, {"literal":"o"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$78"]},
    {"name": "aggregate_keyword$string$79", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"t"}, {"literal":"d"}, {"literal":"D"}, {"literal":"e"}, {"literal":"v"}, {"literal":"S"}, {"literal":"a"}, {"literal":"m"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$79"]},
    {"name": "aggregate_keyword$string$80", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"c"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"m"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$80"]},
    {"name": "aggregate_keyword$string$81", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"L"}, {"literal":"e"}, {"literal":"n"}, {"literal":"B"}, {"literal":"y"}, {"literal":"t"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$81"]},
    {"name": "aggregate_keyword$string$82", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"L"}, {"literal":"e"}, {"literal":"n"}, {"literal":"C"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$82"]},
    {"name": "aggregate_keyword$string$83", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"u"}, {"literal":"b"}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$83"]},
    {"name": "aggregate_keyword$string$84", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"u"}, {"literal":"b"}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"B"}, {"literal":"y"}, {"literal":"t"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$84"]},
    {"name": "aggregate_keyword$string$85", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"u"}, {"literal":"b"}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"C"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$85"]},
    {"name": "aggregate_keyword$string$86", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"u"}, {"literal":"b"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$86"]},
    {"name": "aggregate_keyword$string$87", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"u"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$87"]},
    {"name": "aggregate_keyword$string$88", "symbols": [{"literal":"$"}, {"literal":"s"}, {"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$88"]},
    {"name": "aggregate_keyword$string$89", "symbols": [{"literal":"$"}, {"literal":"t"}, {"literal":"o"}, {"literal":"L"}, {"literal":"o"}, {"literal":"w"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$89"]},
    {"name": "aggregate_keyword$string$90", "symbols": [{"literal":"$"}, {"literal":"t"}, {"literal":"o"}, {"literal":"U"}, {"literal":"p"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$90"]},
    {"name": "aggregate_keyword$string$91", "symbols": [{"literal":"$"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$91"]},
    {"name": "aggregate_keyword$string$92", "symbols": [{"literal":"$"}, {"literal":"t"}, {"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$92"]},
    {"name": "aggregate_keyword$string$93", "symbols": [{"literal":"$"}, {"literal":"t"}, {"literal":"y"}, {"literal":"p"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$93"]},
    {"name": "aggregate_keyword$string$94", "symbols": [{"literal":"$"}, {"literal":"w"}, {"literal":"e"}, {"literal":"e"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$94"]},
    {"name": "aggregate_keyword$string$95", "symbols": [{"literal":"$"}, {"literal":"y"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aggregate_keyword", "symbols": ["aggregate_keyword$string$95"]},
    {"name": "meta_start$string$1", "symbols": [{"literal":"4"}, {"literal":"S"}, {"literal":"K"}, {"literal":"f"}, {"literal":"n"}, {"literal":"Q"}, {"literal":"V"}, {"literal":"8"}, {"literal":"C"}, {"literal":"b"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "meta_start", "symbols": ["meta_start$string$1"]},
    {"name": "meta_end$string$1", "symbols": [{"literal":"g"}, {"literal":"3"}, {"literal":"d"}, {"literal":"7"}, {"literal":"N"}, {"literal":"k"}, {"literal":"s"}, {"literal":"g"}, {"literal":"P"}, {"literal":"K"}, {"literal":"Q"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "meta_end", "symbols": ["meta_end$string$1"]},
    {"name": "id_a", "symbols": ["id"]},
    {"name": "id_a", "symbols": ["meta_start", {"literal":" "}, "id", {"literal":" "}, "meta_end"]},
    {"name": "key_a", "symbols": ["key"]},
    {"name": "key_a", "symbols": ["meta_start", {"literal":" "}, "key", {"literal":" "}, "meta_end"]},
    {"name": "string_a", "symbols": ["string"]},
    {"name": "string_a", "symbols": ["meta_start", {"literal":" "}, "string", {"literal":" "}, "meta_end"]},
    {"name": "num_a", "symbols": ["num"]},
    {"name": "num_a", "symbols": ["meta_start", {"literal":" "}, "num", {"literal":" "}, "meta_end"]},
    {"name": "boolean_a", "symbols": ["boolean"]},
    {"name": "boolean_a", "symbols": ["meta_start", {"literal":" "}, "boolean", {"literal":" "}, "meta_end"]}
]
  , ParserStart: "query"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
